name: Variables for docker with secrets and vars
on: push
env:
    CONTAINER_REGISTRY: docker.io
    image_name: nginx516
jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: artifacts
        uses: actions/checkout@v4

      - name: Docker build
        run: docker build -t ${{ env.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/${{ env.image_name }}:latest .

      - name: Docker logins
        run: docker login --username=${{ vars.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}

      - name: Docker publish
        run: docker push ${{ vars.DOCKER_USERNAME }}/${{ env.image_name }}:latest
        # run: docker push ${{ env.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/${{ env.image_name }}:latest

  deploy-job:
    needs: build-job
    runs-on: ubuntu-latest
    steps:
      - name: Docker Deploy
        run: docker run -d -p 8080:80 ${{ vars.DOCKER_USERNAME }}/${{ env.image_name }}:latest
      